revert to the flaky test again to see if retry would help out

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -30,7 +30,7 @@ jobs:
           # test prepare required for tailwind css file required in application erb
           bin/rails test:prepare --trace
           bin/rails test
-      - name: Build and run system tests
+      - name: system-test
         env:
           RAILS_ENV: test
           RAILS_TEST_KEY: ${{ secrets.RAILS_TEST_KEY }}
@@ -41,11 +41,19 @@ jobs:
         if: ${{ failure() }}
         with:
           path: ./tmp/capybara/screenshots/failures_*.png
-      - name: Build and re-run system tests on failure
+      - name: system-test-retry
         if: ${{ failure() }}
         env:
           RAILS_ENV: test
           RAILS_TEST_KEY: ${{ secrets.RAILS_TEST_KEY }}
         run: |
           bin/rails test:system --trace HEADLESS=true CUPRITE=true APP_HOST='127.0.0.1'
+      - name: set the status              # set the workflow status if command failed
+        if: always()
+        run: |
+          if ${{ steps.system-test.outcome=='success' || steps.system-test-retry.outcome=='success' }}; then
+             echo fine
+          else
+             exit 1
+          fi
 
